# Configuration File
##### Database #####
LOGIN_MYSQL: ''
PASSWORD_MYSQL: ''
DATABASE_MYSQL: ''
HOST_MYSQL: 'localhost'

##### Tweet Stream #####
# Access Keys
CONSUMER_KEY_TWITTER: 'SFiHGCeVr6qMGx9pkxvBg'
CONSUMER_SECRET_TWITTER: 'bSu6UDz4TARxGHWqsvCmgJP8JnlJT31IKyaFBJNtcFY'
OAUTH_TOKEN_TWITTER: '88300988-HMfsqoDKvp5LfjSYomtKMqtF0mx70P2Nf5wIjVC6f'
OUATH_TOKEN_SECRET_TWITTER: 'qpbUxivfOyAwLBgYGF1p0R6F4K9WFVaPd2mpmscQgU'
# Terms
TERM_1_TWITTER: '#FaunaUSP'
TERM_2_TWITTER: '#FloraUSP'
TERM_3_TWITTER: '#BioUSP'
TERM_4_TWITTER: '#FaunaBR'
TERM_5_TWITTER: '#FloraBR'
TERM_6_TWITTER: '#BioBR'