# Configuration File
# Created by J. H. Kersul and Adriano Dennanni

##### Database #####
LOGIN_MYSQL: 'bio'
PASSWORD_MYSQL: 'poli'
DATABASE_MYSQL: 'bio'
HOST_MYSQL: 'localhost'

##### Database Tables #####
# Table User
# id_user, username, name, profile_image
USER_TABLE_CREATE: 'id_user BIGINT NOT NULL, username VARCHAR(30) NOT NULL, name VARCHAR(50) NOT NULL, profile_image VARCHAR(200), profile_bio VARCHAR(300), num_followers INT, num_following INT, num_tweets INT, profile_created_at VARCHAR(100), location VARCHAR(200), website VARCHAR(500), user_reputation BIGINT NOT NULL'
PK_USER_TABLE: 'id_user' # Primary Key row

# Table Tweet
# id_tweet, text, img_url, date_tweet, location_lat, location_long, id_user
TWEET_TABLE_CREATE: 'id_tweet BIGINT NOT NULL, text VARCHAR(300), img_url VARCHAR(300), date_tweet DATETIME NOT NULL, latitude FLOAT, longitude FLOAT, urls VARCHAR(1000), id_user BIGINT NOT NULL, tweet_reputation BIGINT NOT NULL, reports  BIGINT NOT NULL'
PK_TWEET_TABLE: 'id_tweet'
FK_TWEET_TABLE: 'id_user' #Set the foreign key of this table that will reference the Primary Key of User Table

##### Tweet Stream #####
# Access Keys
CONSUMER_KEY_TWITTER: 'R1IJzJFHQengOVPgChtEtw'
CONSUMER_SECRET_TWITTER: 'UtWLro4ej62i6QpRoWAs1woFvMddrpP7zHdVbMl43Xo'
OAUTH_TOKEN_TWITTER: '2159617867-WnudYrXPw0dRNZEkO7CP2U2tyG2QL6K5mACuZpy'
OUATH_TOKEN_SECRET_TWITTER: 'cnuINaFA6844F1GUM8R4Q7NjCJDLIC4PVqp78fp8g0T7I'
# Terms for filtering
TERM_1_TWITTER: '#FaunaUSP'
TERM_2_TWITTER: '#FloraUSP'
TERM_3_TWITTER: '#BioUSP'
TERM_4_TWITTER: '#FaunaBR'
TERM_5_TWITTER: '#FloraBR'
TERM_6_TWITTER: '#BioBR'
TERM_7_TWITTER: '#WorldBio'